# Generated by Django 5.1.3 on 2024-11-29 19:13

import django.db.models.deletion
import kb_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'required': 'Post title is required.'}, max_length=200, validators=[kb_app.models.validate_not_empty])),
                ('content', models.TextField(error_messages={'required': 'Post content is required.'}, validators=[kb_app.models.validate_not_empty])),
                ('user_name', models.CharField(default='Anonymous', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(error_messages={'required': 'Comment content is required.'}, validators=[kb_app.models.validate_not_empty])),
                ('user_name', models.CharField(default='Anonymous', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kb_app.post')),
            ],
        ),
    ]
